Bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('bloodapp.urls')),
    path('', include('bloodrequestapp.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloodapp/urls.py
from  django.urls import path
from bloodapp import views


app_name = "bloodapp"
urlpatterns = [
	path('', views.homepage, name='homepage'),
    path('profile/<uuid:user_id>/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

bloodrequestapp/urls.py
from  django.urls import path
from bloodrequestapp import views


app_name = "bloodrequestapp"
urlpatterns = [
	path('donate/', views.blood_donate, name='blood_donate'),
    path('request/', views.blood_request, name='blood_request'),
    path('refer/', views.blood_refer, name='blood_refer'),
    path('incoming_request/', views.incoming_request, name='incoming_request'),
    path('<uuid:user_id>/all-sent-request', views.list_of_request, name='user_requests'),
   
]

bloodapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django_countries.fields import CountryField
from django.urls import reverse
from django.utils.text import slugify
import random
import string
from Bloodbank import settings
from bloodrequestapp.models import UserGroup, Membership
import uuid



def _random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

class User(AbstractUser):

    user_id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False)

    class Meta:
        ordering = ['username']
        verbose_name_plural = 'User'



class Profile(models.Model):

    GENDER = (('m','Male'), ('f','Female'))
    

    user = models.OneToOneField(User,  on_delete=models.CASCADE)
    gender = models.CharField(max_length=1, choices=GENDER)
    phone = models.CharField(max_length=11, blank=True, null=True)
    country = CountryField()
    city = models.CharField(max_length=250)
    address = models.TextField()
    image = models.ImageField(default='default.jpeg',   upload_to='profile_pics')
    blood_group = models.ForeignKey(UserGroup, default=1, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} ({self.user.email})'

bloodrequestapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django_countries.fields import CountryField
from django.urls import reverse
from django.utils.text import slugify
import random
import string
from Bloodbank import settings
from django.contrib.auth import get_user_model
from django.apps import apps

#BloodRequest = apps.get_model('bloodapp', 'BloodRequest')


def _random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))



class BloodRequest(models.Model):

    REQUEST_REASONS = (('1','Blood Loss'),
                        ('2', 'Child Birth'), 
                        ('3', 'Emergency'),
                        ('4', 'Sickle Cell'))

    BLOOD_TYPE = (('A+','A+'), ('B+', 'B+'),
                    ('O+', 'O+'),('O-','O-'),
                    ('A-','A-'),('B-','B-'),
                    ('AB+','AB+'),('AB-','AB-'))


    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='receipient', related_name='blood_requests')
    #receiver = models.ForeignKey(UserGroup, on_delete=models.CASCADE, verbose_name='donor')
    blood_type = models.CharField(max_length=3, choices=BLOOD_TYPE, default=None)
    reason = models.CharField(max_length=50, choices=REQUEST_REASONS)
    message = models.TextField(max_length=255)
    request_date = models.DateTimeField(default=timezone.now)

    class Meta:
        get_latest_by = 'request_date'
    
    def __str__(self):
        return f'{self.sender.username} sends a blood request. '

class UserGroup(models.Model):

    BLOOD_GROUP = (('A+','A+'), ('B+', 'B+'),
                    ('O+', 'O+'),('O-','O-'),
                    ('A-','A-'),('B-','B-'),
                    ('AB+','AB+'),('AB-','AB-'))

    group_name = models.CharField(max_length=100)
    group_code = models.CharField(max_length=3, choices=BLOOD_GROUP)
    group_slug = models.SlugField(max_length=200, unique=True, blank=True)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Membership', related_name='usergroups')
    request = models.ManyToManyField(BloodRequest,related_name ='usergroups')


    class Meta:
        verbose_name = "Blood Group's"
        verbose_name_plural = verbose_name

    def get_all_request(self):
        for message in self.request.values_list('message', flat=True):
            print(message)



    def unique_slug_generator(self, new_slug=None):

        if new_slug is not None:
            slug = new_slug
        else:
            slug = slugify(self.group_name)
        
        Klass = self.__class__
        qs_exists  = Klass.objects.filter(group_slug=slug).exists()
        if qs_exists:
            new_slug = f'{slug}-{_random_string_generator(4)}'
            return self.unique_slug_generator(new_slug=new_slug)
        return slug

    def save(self, *args, **kwargs):
        self.group_slug = self.unique_slug_generator()
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.group_code




class Membership(models.Model):

    individual  = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.SET_DEFAULT)
    group = models.ForeignKey(UserGroup, default=1, on_delete=models.SET_DEFAULT)
    Date_joined = models.DateField(default=timezone.now)

    def __str__(self):
        return  f'{Membership.objects.all().count()} members are available.'

bloodapp/forms.py
from django import forms
from .models import User, Profile
from bloodrequestapp.models import Membership, UserGroup,  BloodRequest
from allauth.account.forms import SignupForm
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget



class CustomSignUpForm(SignupForm):

    BLOOD_GROUP = (('A+','A+'), ('B+', 'B+'),
                    ('O+', 'O+'),('O-','O-'),
                    ('A-','A-'),('B-','B-'),
                    ('AB+','AB+'),('AB-','AB-'))

    blood_group = forms.CharField(max_length=5, widget=forms.Select(choices=BLOOD_GROUP), required=True)
    country = CountryField().formfield()
    city = forms.CharField(max_length=250, required=True)
    #address = forms.CharField(max_length=200, widget=forms.Textarea, required=True)
    
    

    def signup(self, request, user):
        
        user.save()
        #user.profile.address = self.cleaned_data['address']
        #user.profile.save()

        return user

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields  =  ['phone','country','city','address','blood_group','image']

class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        fields = ['name','email','message']

bloodapp/views.py
from django.shortcuts import render, redirect
from .models import User, Profile
from bloodrequestapp.models import Membership, UserGroup, BloodRequest
from django.urls import reverse
from .forms import UserUpdateForm, ProfileUpdateForm, ContactUsForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import HttpResponse


def homepage(request):
	
	form = ContactUsForm()
	return render(request, 'homepage.html', {'form': form})

@login_required
def dashboard(request):
	return render(request, "dashboard.html")

@login_required
def profile(request, user_id):
	
	context = {}

	try:
		user = User.objects.get(user_id=user_id)
	except User.DoesNotExist:
		return HttpResponse('no user')

	if request.method == 'POST':
		user_form = UserUpdateForm(request.POST or None, instance=user)
		profile_form = ProfileUpdateForm(request.POST or None, request.FILES, instance=user.profile)

		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.success(request, f'profile updated successfuly')
			print("It updated")
			return redirect('bloodapp:profile', user_id)
		else:
			user_form = UserUpdateForm(instance=user)
			profile_form = ProfileUpdateForm(instance=user.profile)
			print("Did not update")
	
	print("Just rendererd")
	user_form = UserUpdateForm(instance=user)
	profile_form = ProfileUpdateForm(instance=user.profile)

	context = {'user': user, 'profile_form': profile_form, 'user_form': user_form}
	return render(request, 'bloodapp/profile.html', context)
	

def about(request):
	return HttpResponse('These is about page.')
	#return render(request, 'bloodapp/profile.html', context)


def contact_us(request):

	if request.method == 'POST':
		form = ContactUsForm(request.POST)
		if form.is_valid():
			
			name = form.cleaned_data['name']
			sender = form.cleaned_data['email']
			message = form.cleaned_data['message']
			subject = '{} contact us on blood app.'.format(name)
			recipients = ['tankoraphael@gmail.com']

			send_mail(subject, message, sender, recipients)
			messages.success(request, f'message sent successfully.')
			return redirect('bloodapp:homepage')
		else:
			messages.error(request, f'Bad request, resend message.')
			return redirect('bloodapp:homepage')
	else:
		form = ContactUsForm()
	return render(request, 'homepage.html', {'form': form})

templates/bloodapp/donate.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Donate{% endblock %}
   
{% block content %}

<div class="container">
    
  </div>

  <!-- INCOMING REQUESTS -->


    <div class="center">
        <div class="row">
            <div class="col-md-6">
                {{request.request_date}}
                <div class="chip">
                    <img src="{% static 'bloodapp/img/eagle.jpg' %}" width="96">
                    {{request.message}}
                </div>
            </div>
            <div class="col-md-4 right">
                <button type="button" class="btn btn-primary">View <span class="badge"></span></button>
            </div>
        </div> 
   </div>
    
      <div class="center">
        <div class="row">
            <div class="col-md-6">
                {{request.request_date}}
                <div class="chip">
                    <img src="{% static 'bloodapp/img/eagle.jpg' %}" width="96">
                    {{request.message}}
                </div>
            </div>
            <div class="col-md-4 right">
                <button type="button" class="btn btn-primary">View <span class="badge"></span></button>
            </div>
        </div> 
   </div>
    
   
     <div class="center">
        <div class="row">
            <div class="col-md-6">
                {{request.request_date}}
                <div class="chip">
                    <img src="{% static 'bloodapp/img/eagle.jpg' %}" width="96">
                    {{request.message}}
                </div>
            </div>
            <div class="col-md-4 right">
                <button type="button" class="btn btn-primary">View <span class="badge"></span></button>
            </div>
        </div> 
   </div>
    
   
   
   
   

   {% endblock %}

templates/bloodapp/incoming_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}incoming request{% endblock %}
   
{% block content %}
<div class="container">
    
</div>

  <!-- INCOMING REQUESTS -->
  {% for request in incoming_request %}
   <div class="center">
    
        <div class="userInfo text-center">
            <h4><strong>{{request.sender.username}}</strong></h4>
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Reason For Request: {{request.get_reason_display}}</strong> </div>
                <div class="panel-body">{{request.message}}</div>
                <div class="panel-heading"><strong>Bloodgroup</strong> </div>
                <div class="panel-body">{{request.blood_type}}</div>
            </div>
            <div class="row">
                <button style="background-color: rgb(216, 24, 24); color: aliceblue;" type="button" class="btn btn-inverse ">Donate</button>
                <button type="button" class="btn btn-inverse">Refer</button>
            </div>
        </div>
     </div>
    {% empty %}
        <h4 style="text-align:center"><strong>No Incoming request recently</strong></h4>
    {% endfor%}
 
{% endblock %}

templates/bloodapp/list_of_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Donate{% endblock %}
   
{% block content %}

<div class="container">
    
  </div>

  <!-- INCOMING REQUESTS -->
<h2 style="text-align:center">All Request Placed By The Curent Logged in User </h2>
    {% for request in all_sent_request %}
    <div class="center">
     
        <div class="row">
       
            <div class="col-md-6">
                {{request.request_date}}
                <br>
                {{request.message}}
            </div>
            <div class="col-md-4 right">
                <a href="#" class="btn btn-primary">Edit <span class="badge"></span></a>
                <button type="button" class="btn btn-danger">Delete <span class="badge"></span></button>
            </div>
        </div> 
    
   </div>
    {% empty %}
        <div class="userInfo text-center">
        <h4 >You have not placed any request.</h4>
        </div>   
    {% endfor %}
   {% endblock %}

templates/bloodapp/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



<div class="container">
{% block content %}
   <!-- <h2><a href="{% url 'bloodapp:homepage' %}">Home</a> </h2>-->
    <a href="{% url 'bloodapp:profile' user.user_id %}" style="margin-left: 80%; margin-bottom: 5px" class="btn btn-outline-secondary">Make Request</a> 
        <div class="content-section">
            <div class="media">
                
                <div class="media-body">
                <div class="" style="margin-left:45%">
                    <img src="{{ user.profile.image.url }}"  alt="" class="rounded-circle account-img">
                    <h4 class="account-heading" >{{user.username}}</h4>
                    <p class="text-secondary">{{user.email}}</p>
                </div>
                    
                    <form action="{% url 'bloodapp:profile' user.user_id %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4"> Profile Info </legend>
                            
                            <div class="form-row">
                                <div class="form-group col-md-6 mb-0">
                                {{user_form.email|as_crispy_field}}
                                </div>
                                 <div class="form-group col-md-6 mb-0">
                                {{user_form.username|as_crispy_field}}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3 mb-0">
                                {{profile_form.phone|as_crispy_field}}
                                </div>
                                <div class="form-group col-md-3 mb-0">
                                {{profile_form.blood_group|as_crispy_field}}
                                </div>
                                <div class="form-group col-md-3 mb-0">
                                {{profile_form.country|as_crispy_field}}
                                </div>
                                 <div class="form-group col-md-3 mb-0">
                                    {{profile_form.city|as_crispy_field}}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6 mb-0">
                                    {{profile_form.address|as_crispy_field}}
                                </div>
                                <div class="form-group col-md-4 mb-0">
                                    {{profile_form.image|as_crispy_field}}
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-secondary-info" type="submit">update</button>
                        </div>
                        
                    </form>
                </div>
            </div>  
        </div>

{% endblock %}
</div>

templates/bloodapp/refer.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Donate{% endblock %}
   
{% block content %}
     <div class="container">
    
  </div>
   <div class="center">
     
    <form role="form" >
      <h1><strong>REFER</strong></h1>
      <div class="form-group">
        <label for="Bloodgroup">Bloodgroup</label>
       
        <label for="Reasons">Reasons</label>
        <select class="form-control" aria-placeholder="Blood Group">
          <option>Blood Loss</option>
          <option>Sickle Cell</option>
          <option>Emergency</option>
          <option>Child birth</option>
        </select>
        <div class="form-group">
          <label for="comment">Email</label>
          <input type="email" class="form-control">
          
        </div>
        <div class="form-group">
          <label for="comment">Phone Number</label>
          <input type="text" class="form-control">
          
        </div>
       <div class="form-group">
        <div class="form-group">
          <label for="comment">Other Reason(s)</label>
          <textarea class="form-control" rows="5" id="comment" ></textarea>
          
        </div>
        <div class="row text-center">
          <button style="background-color: red; color: whitesmoke;"type="button" class="btn btn-default "  data-toggle="modal" data-target="#myModal">SEND</button>

          <button style="background-color: rgb(37, 35, 35); color: whitesmoke;"type="button" class="btn btn-default "  data-toggle="modal" data-target="#myModal">CALL</button>

        </div>
        <!-- SUCCESS MODAL -->
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&CircleTimes;</button>
                <h4 class="modal-title">REQUEST IN PROGRESS</h4>
              </div>
              <div class="modal-body">
                <i class="fa fa-cog fa-spin fa-4x"></i>
               <h3> We will notify you once your request is complete</h3>
              </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </form>
   </div>
{% endblock %}

templates/bloodapp/request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Request{% endblock %}
   
{% block content %}
     <div class="container">
    
  </div>
   <div class="center">
     
    <form role="form", id="request_form" action="{% url 'bloodrequestapp:blood_request' %}" method="POST">
       {% csrf_token %}
      <h1><strong>REQUEST</strong></h1>
      <div class="form-group">
        {{form |crispy }}
      </div>
        <button style="background-color: red; color: whitesmoke;"type="submit" class="btn btn-default">Proceed</button><!--data-toggle="modal" data-target="#myModal" -->
        <!-- SUCCESS MODAL -->
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&CircleTimes;</button>
                <h4 class="modal-title">REQUEST IN PROGRESS</h4>
              </div>
              <div class="modal-body">
                <i class="fa fa-cog fa-spin fa-4x"></i>
               <h3> We will notify you once your request is complete</h3>
              </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </form>
   </div>


{% endblock %}