Bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('bloodapp.urls')),
    path('', include('bloodrequestapp.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloodapp/urls.py
from  django.urls import path
from bloodapp import views


app_name = "bloodapp"
urlpatterns = [
	path('', views.homepage, name='homepage'),
    path('profile/<uuid:user_id>/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

bloodrequestapp/urls.py
from  django.urls import path
from bloodrequestapp import views


app_name = "bloodrequestapp"
urlpatterns = [
	path('donate/', views.blood_donate, name='blood_donate'),
    path('request/', views.blood_request, name='blood_request'),
    path('refer/', views.blood_refer, name='blood_refer'),
    path('incoming_request/', views.incoming_request, name='incoming_request'),
    path('<uuid:user_id>/all-sent-request', views.list_of_request, name='user_requests'),
   
]

templates/includes/about.html
{% load static %}
<div  id="about" class="container">
  <div class="col-sm-8 wow fadeInUp">
    <h1 class="head animated fadeInDown "><strong>ABOUT US</strong></h1>
    <h4>0x0x0 is a platform that makes it easy for blood donnors and recipients to connect and make transactions easy.</h4>
    <p>Our platform simplies transactions for those seeking to donate blood, recipients or people who might make referals to others in neeed</p>
  </div>
  <div class="col-sm-4">
    <img class="  info" src="{% static 'bloodapp/img/children.jpeg' %}" style="border: solid 1px #d40404;">  
  </div>
</div>

  <div id="about">
    <div class="container-fluid2">
      
      <div class="row">
        <div class="col-md-4 text-center wow fadeInUp">
          <h1 class="head "><strong>DONATIONS</strong></h1>
          <h1 class="figures wow rubberBand" data-wow-offset="10"  data-wow-iteration="50"><strong>1000</strong></h1>
          <i class="fa fa-medkit fa-4x"></i>
        </div>
        <div class="col-md-4 text-center wow fadeInUp">
          <h1 class="head "><strong>USERS</strong></h1>
          <h1 class="figures wow rubberBand" data-wow-iteration="50" data-wow-offset="10"><strong>1000</strong></h1>
          <i class="fa fa-users fa-4x"></i>
        </div>
        <div class="col-md-4 text-center wow fadeInUp">
          <h1 class="head "><strong>REQUESTS</strong></h1>
          <h1 class="figures wow rubberBand" data-wow-iteration="50" data-wow-offset="10"><strong>1000</strong></h1>
          <i class="fa fa-medkit fa-4x"></i>
        </div>
      </div>
    </div>
  </div>

templates/includes/contact_us.html
{% load static %}
{% load crispy_forms_tags %}
<div id="contact" class="contact-container text-center">
 <div class="row">
   <h1 class="head">CONTACT</h1>
   <div class="col-sm-5">
     <p>Contact us and we'd get back to you in the next 24 hours</p>
      <p> <i class="fa fa-user"></i>  Jos, Plateau State Nigeria</p>     
      <p> <i class="fa fa-envelope"></i>  chatbloodapp@gmail.com</p>     
      <p> <i class="fa fa-phone"></i>  Jos, Plateau State Nigeria</p>      
      
   </div>
   <div class="col-sm-4">
        <div class="row">
            <form action="{% url 'bloodapp:contact_us' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %} 
                    <div class="form-row">
                        <div class="form-group col-md-6 col-sm-4  mb-0">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 col-sm-4 mb-0">
                            {{ form.email|as_crispy_field }}
                        </div>
                    </div>
                    {{ form.message|as_crispy_field }}
                <div class="row">
                    <div class="col-sm-12 form-group ">
                        <button style="background-color: #d40404;" class="btn btn-danger pull-right" type="submit">SEND</button>
                    </div>
                </div>    
            </form>
        </div>
   </div>
 </div>
</div>

templates/includes/footer.html
{% load static %}
<div class="footer text-center">
    <a href="#home" title="To Top"><i class="fa fa-arrow-up fa-3x wow bounce" data-wow-offset="10"  data-wow-iteration="50"></i></a>
    <p>Designed by Team <a href="www.facebook.com/Cloudsync" style="text-decoration: none; color:white; ">CloudSync</a></p>
</div>

templates/includes/homepage_jumbotron.html
{% load static %}
<div class="jumbotron jumbotron bg-cover text-center">
  <div class="overlay"></div>
  <h1 class="animated fadeInUp">
    BloodApp  
  </h1>
  <p class="animated fadeInDown" id="slim-font">We specialize in the delivery and support of bloooooooood</p>
  <button style="background-color: #d40404;" type="button" class="btn btn-danger down">GET STARTED</button>
</div>

templates/includes/messages.html
{% if messages %}
    <div>
        <strong>Messages:</strong>
        <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
        </ul>
    </div>
{% endif %}

templates/includes/nav.html
  {% load static %}
  <!-- ================== nav bar ================== -->
<div class="navbar-fixed">
    <nav class="black">
        <div class="container">
            <div class="nav-wrapper">
                <a href="{% url 'bloodapp:homepage' %}" class="brand-logo  red-text darken-3" style="font-weight: bolder; font-style: oblique; font-family: monospace ;font-size: xx-larger;">LifeBit</a>
                <a href="#" data-target="mobile-nav" class="sidenav-trigger">
                    <i class="material-icons">menu</i>
                </a>

                <ul class="right hide-on-med-and-down">
                    <li>
                        <a href="{% url 'bloodapp:homepage' %}" >Home</a>
                    </li>
                {% if user.is_authenticated %}

                    <li>
                        <a href="{% url 'bloodapp:dashboard' %}">Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodrequestapp:blood_donate' %}">Donate</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodrequestapp:blood_refer' %}">Refer</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodrequestapp:blood_request' %}">View-Request</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodrequestapp:incoming_request' %}">Notification</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodapp:profile' user.user_id %}">Profile</a>
                    </li>
                    <li>
                        <a href="{% url 'account_logout' %}">SignOut</a>
                    </li>

                    {% else %}
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Support</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                      <li>
                          <a href= "{% url 'account_login' %}" class="btn">Login</a>
                      </li>
                      <li>
                          <a href="{% url 'account_signup' %} " class="btn" style="background:red">Register</a>
                      </li>
                    {% endif %}
                </ul>

                {% if user.is_authenticated %}
                    <a href="" class="visible dropdown-trigger" data-target='dropdown1'><i class="fa fa-user-circle fa-2x fa-fw" aria-hidden="true"></i></a>
                    <a href="{% url 'bloodrequestapp:incoming_request' %}" class="visible"><i class="fa fa-bell"></i></a>
                {% else %}
                     <a href= "{% url 'account_login' %}" class="visible btn" style="background:red; margin-top: 10px;">JOIN</a>
                {% endif %}
            </div>
        </div>
    </nav>
</div>


<div class="container" >
    <ul id='dropdown1' class='dropdown-content black ' style="margin-top: 20px">
        <li ><a href="#!" class="red-text">dashboard</a></li>
        <li class="divider" tabindex="-1"></li>
        <li><a href="#!" class="red-text">donate</a></li>
        <li class="divider" tabindex="-1"></li>
        <li><a href="#!" class="red-text">refer</a></li>
        <li class="divider" tabindex="-1"></li>
        <li><a href="{% url 'bloodapp:profile' user.user_id %}" class="red-text">profile</a></li>
        <li class="divider" tabindex="-1"></li>
        <li><a href="{% url 'account_logout' %}" class=" red white-text">Logout</li>
    </ul>
</div>

<div class="container">
    <ul class="sidenav" id="mobile-nav">
        <li>
        <a href="{% url 'bloodapp:homepage' %}">Home</a>
        </li>
                {% if user.is_authenticated %}

                    <li>
                        <a href="{% url 'bloodapp:dashboard' %}">Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodrequestapp:blood_donate' %}">Donate</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodrequestapp:blood_refer' %}">Refer</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodrequestapp:blood_request' %}">View-Request</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodrequestapp:incoming_request' %}">Notification</a>
                    </li>
                    <li>
                        <a href="{% url 'bloodapp:profile' user.user_id %}">Profile</a>
                    </li>
                    <li>
                        <a href="{% url 'account_logout' %}">SignOut</a>
                    </li>

                    {% else %}
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Support</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    {% endif %}
    </ul>

</div>