Bloodbank/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('bloodapp.urls')),
    path('', include('bloodrequestapp.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloodapp/urls.py
from  django.urls import path
from bloodapp import views


app_name = "bloodapp"
urlpatterns = [
	path('', views.homepage, name='homepage'),
    path('profile/<uuid:user_id>/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

bloodrequestapp/urls.py
from  django.urls import path
from bloodrequestapp import views


app_name = "bloodrequestapp"
urlpatterns = [
	path('donate/', views.blood_donate, name='blood_donate'),
    path('request/', views.blood_request, name='blood_request'),
    path('refer/', views.blood_refer, name='blood_refer'),
    path('incoming_request/', views.incoming_request, name='incoming_request'),
    path('<uuid:user_id>/all-sent-request', views.list_of_request, name='user_requests'),
   
]

bloodrequestapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django_countries.fields import CountryField
from django.urls import reverse
from django.utils.text import slugify
import random
import string
from Bloodbank import settings
from django.contrib.auth import get_user_model
from django.apps import apps

#BloodRequest = apps.get_model('bloodapp', 'BloodRequest')


def _random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))



class BloodRequest(models.Model):

    REQUEST_REASONS = (('1','Blood Loss'),
                        ('2', 'Child Birth'), 
                        ('3', 'Emergency'),
                        ('4', 'Sickle Cell'))

    BLOOD_TYPE = (('A+','A+'), ('B+', 'B+'),
                    ('O+', 'O+'),('O-','O-'),
                    ('A-','A-'),('B-','B-'),
                    ('AB+','AB+'),('AB-','AB-'))


    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='receipient', related_name='blood_requests')
    #receiver = models.ForeignKey(UserGroup, on_delete=models.CASCADE, verbose_name='donor')
    blood_type = models.CharField(max_length=3, choices=BLOOD_TYPE, default=None)
    reason = models.CharField(max_length=50, choices=REQUEST_REASONS)
    message = models.TextField(max_length=255)
    request_date = models.DateTimeField(default=timezone.now)

    class Meta:
        get_latest_by = 'request_date'
    
    def __str__(self):
        return f'{self.sender.username} sends a blood request. '

class UserGroup(models.Model):

    BLOOD_GROUP = (('A+','A+'), ('B+', 'B+'),
                    ('O+', 'O+'),('O-','O-'),
                    ('A-','A-'),('B-','B-'),
                    ('AB+','AB+'),('AB-','AB-'))

    group_name = models.CharField(max_length=100)
    group_code = models.CharField(max_length=3, choices=BLOOD_GROUP)
    group_slug = models.SlugField(max_length=200, unique=True, blank=True)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Membership', related_name='usergroups')
    request = models.ManyToManyField(BloodRequest,related_name ='usergroups')


    class Meta:
        verbose_name = "Blood Group's"
        verbose_name_plural = verbose_name

    def get_all_request(self):
        for message in self.request.values_list('message', flat=True):
            print(message)



    def unique_slug_generator(self, new_slug=None):

        if new_slug is not None:
            slug = new_slug
        else:
            slug = slugify(self.group_name)
        
        Klass = self.__class__
        qs_exists  = Klass.objects.filter(group_slug=slug).exists()
        if qs_exists:
            new_slug = f'{slug}-{_random_string_generator(4)}'
            return self.unique_slug_generator(new_slug=new_slug)
        return slug

    def save(self, *args, **kwargs):
        self.group_slug = self.unique_slug_generator()
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.group_code




class Membership(models.Model):

    individual  = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.SET_DEFAULT)
    group = models.ForeignKey(UserGroup, default=1, on_delete=models.SET_DEFAULT)
    Date_joined = models.DateField(default=timezone.now)

    def __str__(self):
        return  f'{Membership.objects.all().count()} members are available.'

bloodapp/forms.py
from django import forms
from .models import User, Profile
from bloodrequestapp.models import Membership, UserGroup,  BloodRequest
from allauth.account.forms import SignupForm
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget



class CustomSignUpForm(SignupForm):

    BLOOD_GROUP = (('A+','A+'), ('B+', 'B+'),
                    ('O+', 'O+'),('O-','O-'),
                    ('A-','A-'),('B-','B-'),
                    ('AB+','AB+'),('AB-','AB-'))

    blood_group = forms.CharField(max_length=5, widget=forms.Select(choices=BLOOD_GROUP), required=True)
    country = CountryField().formfield()
    city = forms.CharField(max_length=250, required=True)
    #address = forms.CharField(max_length=200, widget=forms.Textarea, required=True)
    
    

    def signup(self, request, user):
        
        user.save()
        #user.profile.address = self.cleaned_data['address']
        #user.profile.save()

        return user

class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields  =  ['phone','country','city','address','blood_group','image']

class ContactUsForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        fields = ['name','email','message']

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>

    <title>{% block head_title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <script src="https://kit.fontawesome.com/9dd31e8a30.js" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="{% static 'bloodapp/css/styles.css' %}">

        {% comment %} <link rel="stylesheet" href="{% static 'bloodapp/css/style.css' %}"> {% endcomment %}
        {% comment %} <link rel="stylesheet" href="{% static 'bloodapp/css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'bloodapp/maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'bloodapp/font-awesome-4.7.0/css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'bloodapp/font-awesome-4.7.0/css/font-awesome.min.css' %}"> {% endcomment %}

        {% block extra_head %}{% endblock %}

  </head>

  <body id="home" class="scrollspy">

<!-- ================== Content block ================== -->
<main role="main">
  {% include 'includes/nav.html' %}
</main>
{% include 'includes/messages.html' %}
{% block body %}{% endblock %}

{% block extra_body %}{% endblock %}

  {% comment %} <script src="{% static 'bloodapp/ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js' %}"></script>
  <script src="{% static 'bloodapp/js/script.js' %}"></script>
  <script src="{% static 'bloodapp/maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'bloodapp/js/wow.min.js' %}"></script>
   {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  <script>

      const sideNav = document.querySelector('.sidenav');
        M.Sidenav.init(sideNav, {});

        //SLIDE
        const slider = document.querySelector('.slider');
        M.Slider.init(slider, {
            indicators: false,
            height: 400,
            transition: 500,
            interval: 3000
        });

        document.addEventListener('DOMContentLoaded', function() {
          const sl = document.querySelectorAll('select');
          M.FormSelect.init(sl, {});


          const db = document.querySelectorAll('.dropdown-trigger');
         M.Dropdown.init(db, {});
        });

        window.addEventListener('click', e => {
           console.log(23)
        });


      {% if user.is_authenticated %}
        console.log(window.location)

          var formData = $("#request_form")
          var bloodGroupInput = $("#id_blood_group")
          var reasonInput = $("#id_reason")
          var messageInput = $("#id_message")

          var loc = window.location
          var ws_start = 'ws://'

          if(loc.protocol == 'https'){
            ws_start = 'wss://'
          }
          var end_point = ws_start + loc.host + loc.pathname
          console.log(end_point)
          //socket = new WebSocket(end_point)

          socket.onmessage = function(e){
            console.log('message', e)
          }
          socket.onopen = function(e){
            console.log('message', e)

            formData.submit(function(event){

                let blood_group = bloodGroupInput.val()
                let reason = reasonInput.val()
                let message = messageInput.val()

                var obj = {
                  "blood" : blood_group,
                  "reason": reason,
                  "message": message
                }
                socket.send(JSON.stringify(obj))
            })

          }
          socket.onerror = function(e){
            console.log('message', e)
          }
          socket.onclose = function(e){
            console.log('message', e)
          }





      {% endif %}
    </script>
<!--
     <script src="{% static 'bloodapp/ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js' %}"></script>
  <script src="{% static 'bloodapp/js/script.js' %}"></script>
-->
  </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Home{% endblock %}





  {% block body %}
<div class="container">

</div>



  <div class="center">
    <div class="row">
       <div class="col-sm-4">
         <h3><strong>DONATIONS</strong></h3>
         <p>You can connect people who are in need of blood, to donnors willing to support.</p>
         <span style="font-size: 2em; color:rgb(197, 49, 49);">
           <i  class="fa fa-medkit fa-2x"></i>
           </span>
       </div>
       <div class="col-sm-4">
        <h3><strong>REFERALS</strong></h3>
        <p>You can connect people who are in need of blood, to donnors willing to support.</p>
        <span style="font-size: 2em; color:rgb(197, 49, 49);">
          <i  class="fa fa-calendar fa-2x"></i>
          </span>
      </div>
      <div class="col-sm-4">
        <h3><strong>REQUESTS</strong></h3>
        <p>As a user, You can send requests for people who are willing to donate with reasons.</p>
        <span style="font-size: 2em; color:rgb(197, 49, 49);">
          <i  class="fa fa-user-plus fa-2x"></i>
          </span>
      </div>



    </div>

  </div>



  <div class="center">
    <div class="row">
       <div class="col-sm-4">
         <span style="font-size: 2em; color:rgb(197, 49, 49);">
           <i class="fa fa-medkit fa-3x"></i>
           </span>
       </div>
       <div class="col-sm-8">
         <div class="row">
           <div class="col-sm-12">

            <h2><strong>DONATIONS</strong></h2>
             <p>Connect with people who are in need of blood, support them with your token</p>
             <button  type="button" class="btn btn-default" onclick="window.location.href = ' {% url 'bloodrequestapp:blood_donate' %} ' ";  ' ";>Proceed</button>
           </div>

         </div>
       </div>

    </div>

  </div>

  <div class="center">
   <div class="row">
      <div class="col-sm-4">
        <span style="font-size: 2em; color:rgb(197, 49, 49);">
          <i  class="fa fa-user-plus fa-3x"></i>
          </span>
      </div>
      <div class="col-sm-8">
        <div class="row">
          <div class="col-sm-12">
           <h2><strong>REFERALS</strong></h2>
            <p>You can connect people who are in need of blood, to donnors willing to support.</p>
            <button  type="submit" class="btn btn-default" onclick="window.location.href = ' {% url 'bloodrequestapp:blood_refer' %} ' ";>Proceed</button>
          </div>

        </div>
      </div>

   </div>

 </div>

 <div class="center">
  <div class="row">
     <div class="col-sm-4">
       <span style="font-size: 2em; color:rgb(197, 49, 49);">
         <i  class="fa fa-users fa-3x"></i>
         </span>
     </div>
     <div class="col-sm-8">
       <div class="row">
         <div class="col-sm-12">
          <h2 ><strong>REQUEST</strong></h2>
           <p>As a user, You can send requests for people who are willing to donate with reasons.</p>
          <button type="button" class="btn btn-default" onclick="window.location.href = ' {% url 'bloodrequestapp:blood_request' %} ' ";>Proceed</button>
          </div>

       </div>
     </div>

  </div>

</div>
  {% include 'includes/footer.html' %}

{% endblock %}

templates/homepage.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head_title %}Home{% endblock %}

{% block extra_head %}

<style>
 
</style>

{% endblock %}

{% block body %}
      <section class="section red darken-3 ">
        <div class="container">
        </div> 
      </section>
      <!--Section-->  
    <section class="slider">
        <ul class="slides">
            <li>
              <img src="{% static 'bloodapp/img/donate.jpg' %}"> <!-- random image -->
            </li>
            <li>
              <img src="{% static 'bloodapp/img/donate2.jpg' %}"> <!-- random image -->
            </li>
            <li>
              <img src="{% static 'bloodapp/img/donate3.jpg' %}"> <!-- random image -->
            </li>
        </ul>
    </section>
     

     <section class="section red darken-3">
        <div class="container">
        </div> 
    </section>

    <section id="about" class="section section-about black lighten-3 white-text center scrollspy">
        <div class="container">
          <div class="row">
            <h4 class="center">About <span class="red-text">LifeBit</span></h4>
            <div class="col s12 m4 l4">
              <img class="info" src="{% static 'bloodapp/img/children.jpeg' %}" style="border: solid 1px #d40404;"> 
             
            </div>
            
            <div class="col s12 m2 l2">
            </div>
            <div class="col s12 m6 l6">
                <h5><span class="red-text">LifeBit</span> is a platform that makes it easy for blood donors and recipients to connect and make transactions easly.</h5>
                <p>Our platform:</p>
                <ul >
                  <li>Simplifies transactions for those seeking to donate blood.</li>
                  <li>Permit individuals who make referals to others in need.</li>
                  <li>Connects recipients to possible donors.</li>
                </ul>
              </div>
            </div>
            
          </div>
        </div> 
    </section>

    <section class="section section-icons grey lighten-2 center">
        <div class="container">
            <div class="row">
                <div class="col s12 m4">
                    <div class="card-panel ">
                        <i class="material-icons large red-text">share</i>
                        <h3 class="red-text">Donations</h3>
                        <h5><strong>1000</strong></h5>
                    </div>   
                </div>
                <div class="col s12 m4">
                    <div class="card-panel ">
                        <i class="material-icons large red-text">people</i>
                        <h3 class="red-text">Users</h3>
                        <h5><strong>1000</strong></h5>
                    </div>   
                </div>
                <div class="col s12 m4">
                    <div class="card-panel ">
                        <i class="material-icons large red-text">pan_tool</i>
                        <h3 class="red-text">Request</h3>
                        <h5><strong>1000</strong></h5>
                    </div>   
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="section coral lighten-2 section-contact scrollspy">
      <div class="container">
        <h4 class="center"> Contact <span class="red-text">LifeBit</span></h4>
            <div class="row">
            
              <div class="col s12 m6">
                <div class="card-panel red white-text center">
                    <i class="material-icons">email</i>
                    <h4>Contact us for more Info</h4>
                    <p class="valign-wrapper center-align"><i class="material-icons small">email</i> BitLife@yahoo.com</p>
                    <p class="valign-wrapper center-align"><i class="material-icons small ">phone</i> +2347035734905</p>
                </div>
                
            </div>
            <div class="col s12 m6">
                <div class="card-panel">
                    <h4 class="red-text">Please fillout these form.</h4>
                    <div class="input-field">
                        <input type="text" placeholder="Enter a name">
                    </div>
                    <div class="input-field">
                        <input type="text" placeholder="Enter a email">
                    </div>
                    <div class="input-field">
                        <input type="text" placeholder="Enter a phone">
                    </div>
                    <div class="input-field">
                        <textarea class="materialize-textarea" placeholder="Enter message"></textarea>
                    </div>
                    <div class="input-field">
                        <input type="submit" value="Submit" class="btn float-right" id="myBtn">
                    </div>
                </div>
            </div>
          
              
          
          </div>
      </div>
  </section>
  <section class="section section-follow red darken-2 white-text center">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h4>Follow Us</h4>
                <p>Follow us on social media for special offers</p>
                <a href="" class="white-text">
                    <i class="fab fa-facebook fa-2x"></i>
                </a>
                <a href="" class="white-text">
                    <i class="fab fa-twitter fa-2x"></i>
                </a>
                <a href="" class="white-text">
                    <i class="fab fa-linkedin fa-2x"></i>
                </a>
                <a href="" class="white-text">
                    <i class="fab fa-google-plus fa-2x"></i>
                </a>
            </div>
        </div>
    </div>
</section>
  <footer class="section black lighten-5 white-text center">
    
    <p class="flow-text"> <span class="red-text">LifeBit</span>&copy; 2020</p>
</footer>

{% endblock %}